name: Tests

on: [pull_request, push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build
        uses: docker/build-push-action@v3
  src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

  tmca-tester_coverage:
    runs-on: ubuntu-latest
    container:
      image: openjdk:17-jdk-slim-buster
      options: --user root
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd jpo-security-svcs/
          ./mvnw org.jacoco:jacoco-maven-plugin:prepare-agent package
          ./mvnw org.jacoco:jacoco-maven-plugin:report package
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: tmca-tester
          path: tcma-tester/target
          if-no-files-found: error

  sonar:
    needs: [src, tmca-tester_coverage]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download code coverage results
        uses: actions/download-artifact@v3
        with:
          name: tmca-tester
          path: tmca-tester/target

      - name: Setup SonarScanner
        uses: warchant/setup-sonar-scanner@v4
        with:
          version: 4.8.0.2856
      - name: Generate sonar properties file
        run: |
          cat <<EOF > /tmp/sonar-scanner.properties
          sonar.host.url=https://sonarcloud.io
          sonar.coverage.jacoco.xmlReportPaths=$GITHUB_WORKSPACE/tmca-tester/target/site/jacoco/jacoco.xml
          #sonar.exclusions=**/__init__.py,**/*test*.py,**/test/**
          #sonar.coverage.exclusions=**/__init__.py,**/*test*.py,**/test/**
          sonar.java.binaries=$GITHUB_WORKSPACE/tmca-tester/target/
          #sonar.javascript.lcov.reportPaths=web_app_client/lcov.info
          sonar.modules=src,tmca-tester
          sonar.projectBaseDir=$GITHUB_WORKSPACE
          sonar.projectKey=usdot-jpo-ode_jpo-security-svcs
          sonar.organization=usdot-jpo-ode-1
          #sonar.projectName=cda-telematics
          tmca-tester.sonar.projectBaseDir=$GITHUB_WORKSPACE/tmca-tester
          tmca-tester.sonar.sources=src
          sonar.modules=jpo-security-svcs
          jpo-security-svcs.sonar.projectBaseDir  = $GITHUB_WORKSPACE
          jpo-security-svcs.sonar.sources         = src
          EOF
      - name: Run SonarScanner
        uses: usdot-fhwa-stol/actions/sonar-scanner@main
        with:
          sonar-properties-path: /tmp/sonar-scanner.properties
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          working-dir: $GITHUB_WORKSPACE
